name: TEST Bug Report
description: File a bug report
title: "BUG: [Give the Bug a Name]"
labels: ["bug", "triage"]
assignees:
  - marshallrobinson
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen? Please use concise and descriptive detail. Please attach screenshots of the bug to this text-box.
      value: |
      1.
      2.
      3.
      ...
      validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Browser Version
      description: What browser(s) and version(s) do you seeing the problem on?
      placeholder: Chrome Version 95.0.4638.69 (Official Build) (64-bit)
    validations:
      required: true
  
