name: TEST Bug Report
description: File a bug report
title: "BUG: [Give the Bug a Name]"
labels: ["bug", "triage", "considering"]
assignees:
  - marshallrobinson
body:
  - type: textarea
    id: repro
    attributes:
      label: What happened?
      description: "How do you trigger this bug? Please walk us through it step by step. Please attach screenshots of the bug to this text-box."
      value: |
        1. 
        2.
        3.
    validations:
      required: true
 - type: textarea
    id: repro
    attributes:
      label: What did you expect to happen?
      description: "Tell us what you expected to happen"
      placeholder: Please use concise and descriptive detail.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Browser Version
      description: What browser(s) and version(s) do you seeing the problem on?
      placeholder: Chrome Version 95.0.4638.69 (Official Build) (64-bit)
    validations:
      required: true
  
