name: This Application Needs a New Layer(s)
description: Use this form to request a new layer(s) gets added to this application
title: This Application Needs a New Layer(s)
labels: ["enhancement", "new data"]
assignees:
  - nmpayne, marshallrobinson, mackenzie-cope
body:
  - type: textarea
    id: requestReason
    attributes:
        label: Why do you feel this application needs what you're requesting?
        placeholder: I need this new layer added because [...] (for each layer)
    validations:
        required: true
  - type: textarea
    id: valueReason
    attributes:
        label: Describe the layer(s) you'd like to add
        placeholder: A clear and concise description of the new layer(s) you'd like to add.
    validations:
        required: true
  - type: textarea
    id: moreContext
    attributes:
        label: Additional Context
        placeholder: Add any other context or screenshots about the new layer here.
    validations:
        required: false
  - type: textarea
    id: popupDetails
    attributes:
        label: Popup Formatting
        description: Following the current popup-formatting of other layers in this applications, what attributes would you like displayed for the new layer(s)?
        placeholder: Popup Title, Attribute Name, Attribute Value (w/desired units if necessary), etc.
    validations:
        required: true
  - type: textarea
    id: reviewCheckDatabase
    attributes:
        label: Who has reviewed your database so far? (e.g. Schema, Field Types, Topology, etc.)
        placeholder: Tag reviewer's Github username here so they can verify (e.g. @nmpayne); Required review - GIS Analyst, GIS Manager, Database Manager; Tag @marshallrobinson if you need a Github username created for reviewer
    validations:
        required: true
  - type: textarea
    id: reviewCheckScience
    attributes:
        label: Who has reviewed your science and grammar so far for both your data and application panels?
        placeholder: Tag reviewer's username here so they can verify (e.g. @geowomansteph=Steph Carney); Required review - peer, program manager, technical reviewer (if data is in full sentence format); Tag @marshallrobinson if you need a Github username created for reviewer
    validations:
        required: true      
  - type: textarea
    id: panelEdits
    attributes:
        label: Copy/paste all text for application panels here (e.g. About, Supplemental Data, Explanation)
        value: |
          About Panel:
          Suplemental Data:
          Explanation:
    validations:
        required: true      
  - type: input
    id: dataLocation
    attributes:
        label: Folder path of data
        placeholder: G:\Shared drives\UGS_Shared\...
    validations:
        required: true
