name: TEST Suggest Static Text Edit
description: test
title: Suggest Static Text Edit
labels: ["enhancement"]
assignees:
  - marshallrobinson, geowomansteph
body:
  - type: input
    id: panelName
    attributes:
        label: Where is the text you are suggesting changes for?
        placeholder: About Panel, Database Contents, Explanation, etc.
    validations:
        required: true
  - type: textarea
    id: oldText
    attributes:
        label: What does the current text say?
        placeholder: Copy/paste from the current application (be sure to include hyperlinks and any special formatting). If you maintain your application's text in a Doc, please paste a link to it here.
    validations:
        required: true
  - type: textarea
    id: newText
    attributes:
        label: What do you propose the new text says?
        placeholder: I need this new data added because [...] (for each layer)
    validations:
        required: true
  - type: textarea
    id: reviewCheckGrammar
    attributes:
        label: Who has reviewed your proposed text so far?
        placeholder: If longer than a few words, it must go through review - peer, program manager, technical reviewer
    validations:
        required: true
