name: Suggest Static Text Edit
description: Use this form to request a change to text that is in one of the application menus/panels
title: Suggest Static Text Edit
labels: ["enhancement"]
assignees:
  - marshallrobinson, geowomansteph
body:
  - type: input
    id: panelName
    attributes:
        label: Where is the text you are suggesting changes for?
        placeholder: About Panel, Database Contents, Explanation, etc.
    validations:
        required: true
  - type: textarea
    id: oldText
    attributes:
        label: What does the current text say?
        placeholder: Copy/paste from the current application (be sure to include hyperlinks and any special formatting). If you maintain your application's text in a Doc, please paste a link to it here.
    validations:
        required: true
  - type: textarea
    id: newText
    attributes:
        label: What do you propose the new text says?
        placeholder: I need this new data added because [...] (for each layer)
    validations:
        required: true
  - type: textarea
    id: reviewCheckGrammar
    attributes:
        label: Who has reviewed your proposed text so far?
        placeholder: Tag reviewer's username here so they can verify (e.g. @geowomansteph=Steph Carney); Required review - peer, program manager, technical reviewer (if data is in full sentence format); Tag @marshallrobinson if you need a Github username created for reviewer
    validations:
        required: true
